# Generated by Django 5.1.1 on 2024-11-07 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.PositiveIntegerField()),
                ('max_duration', models.PositiveIntegerField()),
                ('min_duration', models.PositiveIntegerField()),
                ('avg_duration', models.FloatField()),
                ('max_page_views', models.PositiveIntegerField()),
                ('min_page_views', models.PositiveIntegerField()),
                ('avg_page_views', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
