# Generated by Django 5.1.1 on 2024-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvisitorstatistics',
            name='homepage_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
