# Generated by Django 5.1.1 on 2024-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_emailuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
