# Generated by Django 5.1.1 on 2024-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_emailuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('facebook', 'Facebook'), ('kakao', 'Kakao'), ('naver', 'Naver')], default='manual', max_length=20),
        ),
    ]
