# Generated by Django 3.2.23 on 2024-08-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='artist/')),
                ('description', models.CharField(max_length=200, null=True)),
                ('text_person', models.JSONField(default=list)),
                ('like', models.IntegerField(default=0)),
                ('hot_point', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('hide', models.BooleanField(default=True)),
                ('person', models.ManyToManyField(blank=True, related_name='artist', to='personapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='정보', max_length=200)),
                ('text', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_descriptions', to='artistapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('update_description', models.TextField(blank=True, null=True)),
                ('hide', models.BooleanField(default=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='artistapp.artist')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='sub_titles',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artistapp.Subtitle'),
        ),
        migrations.AddField(
            model_name='artist',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HonoraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveIntegerField(choices=[(1, '1분기'), (2, '2분기'), (3, '3분기'), (4, '4분기')])),
                ('frame_style', models.CharField(max_length=100)),
                ('hot_point', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('major', '메이저'), ('minor', '마이너')], max_length=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorary_entries', to='artistapp.artist')),
            ],
            options={
                'unique_together': {('artist', 'year', 'quarter', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ArtistPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistapp.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artist')},
            },
        ),
    ]
