# Generated by Django 3.2.23 on 2024-09-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('singapp', '0001_initial'),
        ('artistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
                ('appearance_period', models.CharField(max_length=100, null=True)),
                ('period', models.CharField(max_length=100, null=True)),
                ('like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('artist', models.ManyToManyField(blank=True, related_name='genre', to='artistapp.Artist')),
                ('beginning_song', models.ManyToManyField(blank=True, related_name='beginning_song', to='singapp.Sing')),
                ('derived_genres', models.ManyToManyField(blank=True, related_name='derives_into', to='genreapp.Genre')),
                ('masterpiece_song', models.ManyToManyField(blank=True, related_name='masterpiece_song', to='singapp.Sing')),
                ('origins', models.ManyToManyField(blank=True, related_name='originated_from', to='genreapp.Genre')),
                ('related_genres', models.ManyToManyField(blank=True, related_name='related_to_genres', to='genreapp.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('update_description', models.TextField(blank=True, null=True)),
                ('hide', models.BooleanField(default=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='genreapp.genre')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='sub_titles',
            field=models.ManyToManyField(blank=True, related_name='genres', to='genreapp.Subtitle'),
        ),
        migrations.AddField(
            model_name='genre',
            name='subgenres',
            field=models.ManyToManyField(blank=True, related_name='parent_genres', to='genreapp.Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='정보', max_length=100)),
                ('text', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_descriptions', to='genreapp.genre')),
            ],
        ),
    ]
