# Generated by Django 3.2.23 on 2024-08-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleapp', '0001_initial'),
        ('artistapp', '0001_initial'),
        ('projectapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ManyToManyField(blank=True, related_name='homepage', to='articleapp.Article')),
                ('artist', models.ManyToManyField(blank=True, related_name='homepage', to='artistapp.Artist')),
                ('person', models.ManyToManyField(blank=True, related_name='homepage', to='personapp.Person')),
                ('project', models.ManyToManyField(blank=True, related_name='homepage', to='projectapp.Project')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
