# Generated by Django 3.2.23 on 2024-09-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singapp', '0001_initial'),
        ('instrumentapp', '0001_initial'),
        ('artistapp', '0001_initial'),
        ('genreapp', '0001_initial'),
        ('articleapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0001_initial'),
        ('albumapp', '0001_initial'),
        ('personapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('hide', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('board_type', models.CharField(choices=[('자유게시판', '자유게시판'), ('노래추천', '노래추천'), ('구인', '구인'), ('공연후기', '공연후기'), ('홍보', '홍보')], default='자유게시판', max_length=50, verbose_name='게시판 종류')),
                ('album', models.ManyToManyField(blank=True, related_name='community', to='albumapp.Album')),
                ('article', models.ManyToManyField(blank=True, related_name='community', to='articleapp.Article')),
                ('artist', models.ManyToManyField(blank=True, related_name='community', to='artistapp.Artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='community', to='genreapp.Genre')),
                ('instrument', models.ManyToManyField(blank=True, related_name='community', to='instrumentapp.Instrument')),
                ('person', models.ManyToManyField(blank=True, related_name='community', to='personapp.Person')),
                ('project', models.ManyToManyField(blank=True, related_name='community', to='projectapp.Project')),
                ('sing', models.ManyToManyField(blank=True, related_name='community', to='singapp.Sing')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
